// Copyright 2026, Diogo Costa, diogo.costa@uevora.pt
// This file is part of the FLUXOS model.

// This program, FLUXOS, is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Copyright 2019, Diogo Costa
// Initialization routines for triangular mesh

#include "tri_initiate.h"
#include "tri_mesh_io.h"
#include <iostream>
#include <cmath>
#include <cctype>
#include <algorithm>
#include <map>
#include <string>

// ============================================================================
// Initialize triangular mesh solution
// ============================================================================
void tri_initiation(
    GlobVar& ds,
    TriMesh& mesh,
    TriSolution& sol,
    int nchem,
    std::ofstream& logFLUXOSfile)
{
    const int ncells = mesh.num_cells;
    const int nedges = mesh.num_edges;

    // Allocate solution arrays
    sol.allocate(ncells, nedges, nchem);

    logFLUXOSfile << "\nTriangular mesh initialization:" << std::endl;
    logFLUXOSfile << "  Cells: " << ncells << std::endl;
    logFLUXOSfile << "  Edges: " << nedges << std::endl;

    // ---- Interpolate bed elevation ----
    if (mesh.has_vertex_elevations) {
        // VERTEX Z PATH: DEM elevations embedded in mesh vertex z-coordinates
        // (generated by supporting_scripts/1_Model_Config/model_config_template.py)
        // Cell elevation = arithmetic mean of its 3 vertex z values
        std::cout << "Using vertex elevations from mesh file (Python preprocessed DEM)" << std::endl;
        logFLUXOSfile << "  Elevation source: vertex z-coordinates from mesh file" << std::endl;

        for (int ci = 0; ci < ncells; ci++) {
            const Vertex& v0 = mesh.vertices[mesh.cells[ci].verts[0]];
            const Vertex& v1 = mesh.vertices[mesh.cells[ci].verts[1]];
            const Vertex& v2 = mesh.vertices[mesh.cells[ci].verts[2]];

            double zb_val = (v0.z + v1.z + v2.z) / 3.0;

            // NODATA check: if ANY vertex has zero/negative elevation,
            // treat the cell as inactive (Neumann BC). This catches boundary
            // triangles where some vertices fall outside the DEM domain.
            // Also mark very small cells (area < 2 m²) as inactive — these are
            // numerical artifacts near sharp topographic features that act as sinks.
            bool has_nodata_vertex = (v0.z <= 0.0 || v1.z <= 0.0 || v2.z <= 0.0);
            bool is_tiny_cell = (mesh.cells[ci].area < 2.0);
            if (zb_val <= 0.0 || has_nodata_vertex || is_tiny_cell) {
                sol.innerNeumannBCWeir[ci] = 1.0f;
                // Average from valid neighbor cells
                double sum_zb = 0.0;
                int count = 0;
                for (int e = 0; e < 3; e++) {
                    int nj = mesh.cells[ci].neighbors[e];
                    if (nj >= 0) {
                        const Vertex& nv0 = mesh.vertices[mesh.cells[nj].verts[0]];
                        const Vertex& nv1 = mesh.vertices[mesh.cells[nj].verts[1]];
                        const Vertex& nv2 = mesh.vertices[mesh.cells[nj].verts[2]];
                        double nzb = (nv0.z + nv1.z + nv2.z) / 3.0;
                        if (nzb > 0.0) {
                            sum_zb += nzb;
                            count++;
                        }
                    }
                }
                if (count > 0) {
                    zb_val = sum_zb / count;
                }
            } else {
                zb_val = std::fabs(zb_val);
            }

            sol.zb[ci] = zb_val;
            sol.z[ci] = zb_val;   // Initially dry (water surface = bed)
            sol.h[ci] = 0.0;
            sol.ks[ci] = ds.hdry;
            sol.ldry[ci] = 1.0f;  // Start dry
        }
    } else {
        // DEM GRID PATH: Original interpolation from regular grid stored in ds.zb
        // Nearest-neighbor from DEM grid to triangle centroids
        logFLUXOSfile << "  Elevation source: DEM grid interpolation" << std::endl;

        for (int ci = 0; ci < ncells; ci++) {
            double cx = mesh.cells[ci].cx;
            double cy = mesh.cells[ci].cy;

            // Convert to grid coordinates
            double gx = (cx - ds.XLLCORNER) / ds.dxy;
            double gy = (cy - ds.YLLCORNER) / ds.dxy;

            // Grid indices
            int ix = static_cast<int>(std::floor(gx));
            int iy = static_cast<int>(std::floor(gy));

            // Clamp to valid range
            ix = std::max(1, std::min(ix, static_cast<int>(ds.NROWS)));
            iy = std::max(1, std::min(iy, static_cast<int>(ds.NCOLS)));

            // Use nearest-neighbor for simplicity (can upgrade to bilinear)
            double zb_val = (*ds.zb)(ix, iy);

            // Check for NODATA
            if (zb_val == ds.NODATA_VALUE || zb_val == 0.0) {
                sol.innerNeumannBCWeir[ci] = 1.0f;
                // Average from valid neighbors
                double sum_zb = 0.0;
                int count = 0;
                for (int e = 0; e < 3; e++) {
                    int nj = mesh.cells[ci].neighbors[e];
                    if (nj >= 0) {
                        double ncx = mesh.cells[nj].cx;
                        double ncy = mesh.cells[nj].cy;
                        double ngx = (ncx - ds.XLLCORNER) / ds.dxy;
                        double ngy = (ncy - ds.YLLCORNER) / ds.dxy;
                        int nix = std::max(1, std::min(static_cast<int>(std::floor(ngx)),
                                                        static_cast<int>(ds.NROWS)));
                        int niy = std::max(1, std::min(static_cast<int>(std::floor(ngy)),
                                                        static_cast<int>(ds.NCOLS)));
                        double nzb = (*ds.zb)(nix, niy);
                        if (nzb != ds.NODATA_VALUE && nzb != 0.0) {
                            sum_zb += std::fabs(nzb);
                            count++;
                        }
                    }
                }
                if (count > 0) {
                    zb_val = sum_zb / count;
                }
            } else {
                zb_val = std::fabs(zb_val);
            }

            sol.zb[ci] = zb_val;
            sol.z[ci] = zb_val;  // Initially dry (water surface = bed)
            sol.h[ci] = 0.0;
            sol.ks[ci] = ds.hdry;  // Same as regular mesh: hdry from ks
            sol.ldry[ci] = 1.0f;   // Start dry
        }
    }

    // ---- Find inflow cell + injection patch ----
    //
    // On the regular mesh the inflow Q [m³/s] is added to a single cell
    // of fixed area dxy² (e.g. 900 m² for a 30 m DEM). On a triangular
    // mesh the picked triangle may have area 10–400 m² depending on
    // local refinement — so injecting Q*dt into one small triangle
    // produces an unphysical depth spike (≥ 1 m per timestep) that
    // dominates the flow pattern.
    //
    // Fix: pick all triangular cells whose centroid falls within a disk
    // of radius ≈ dxy of the inflow point, and later (tri_add_inflow)
    // distribute the volume Q*dt uniformly across them by area. Net
    // effect:
    //   * total volume added per step = Q*dt (mass-conservative)
    //   * per-cell depth rise = Q*dt / total_patch_area
    //     ≈ Q*dt / (π·dxy²)  — the same scale as the regular mesh
    // Falls back to the single nearest cell if no triangles are inside
    // the disk (e.g. extremely coarse meshes).
    if (ds.inflow_xcoord != 0 || ds.inflow_ycoord != 0) {
        double inflow_x = static_cast<double>(ds.inflow_xcoord);
        double inflow_y = static_cast<double>(ds.inflow_ycoord);

        int inflow_cell = mesh.find_cell(inflow_x, inflow_y);
        if (inflow_cell >= 0) {
            logFLUXOSfile << "  Inflow cell found: " << inflow_cell
                          << " at (" << mesh.cells[inflow_cell].cx << ", "
                          << mesh.cells[inflow_cell].cy << ")" << std::endl;
            // Store inflow cell index in ds for later use
            // We use inflow_nrow to store the cell index for triangular mesh
            ds.inflow_nrow = inflow_cell;
            ds.inflow_ncol = 0;  // Not used for triangular mesh

            // Build injection patch: cells whose centroid is within
            // radius = ds.dxy (DEM cellsize) of the inflow point.
            const double R = std::max(static_cast<double>(ds.dxy), 1.0);
            const double R2 = R * R;
            ds.inflow_patch_cells.clear();
            ds.inflow_patch_total_area = 0.0;
            for (int ci = 0; ci < mesh.num_cells; ci++) {
                // Skip flagged-inactive cells so we don't inject into
                // NODATA regions that were neutralised in the zb loop
                // above (innerNeumannBCWeir[ci] == 1.0f).
                if (sol.innerNeumannBCWeir[ci] == 1.0f) continue;
                const double dx = mesh.cells[ci].cx - inflow_x;
                const double dy = mesh.cells[ci].cy - inflow_y;
                if (dx*dx + dy*dy <= R2) {
                    ds.inflow_patch_cells.push_back(ci);
                    ds.inflow_patch_total_area += mesh.cells[ci].area;
                }
            }
            if (ds.inflow_patch_cells.empty()) {
                // Fallback: single cell.
                ds.inflow_patch_cells.push_back(inflow_cell);
                ds.inflow_patch_total_area = mesh.cells[inflow_cell].area;
            }
            logFLUXOSfile << "  Inflow patch: "
                          << ds.inflow_patch_cells.size() << " cells, "
                          << "total area " << ds.inflow_patch_total_area
                          << " m² (R=" << R << " m)" << std::endl;
        } else {
            logFLUXOSfile << "  WARNING: Inflow location not found in mesh!" << std::endl;
        }
    }

    // Apply boundary conditions
    tri_apply_boundary_conditions(ds, mesh, sol);

    logFLUXOSfile << "  Initialization complete." << std::endl;
}

// ============================================================================
// Apply boundary conditions based on mesh boundary tags
// ============================================================================
void tri_apply_boundary_conditions(
    GlobVar& ds,
    TriMesh& mesh,
    TriSolution& sol)
{
    // Translate the JSON BOUNDARY_CONDITIONS map onto edge.boundary_tag.
    //
    // The mesh file stores the original Gmsh / Triangle physical tag
    // (commonly 1 for all perimeter edges). The solver's flux routines
    // (tri_solver_wet, tri_solver_dry) branch on the MAGIC number 3 to
    // mean "wall" and treat everything else as transmissive outflow.
    // Without this translation, the JSON setting is silently ignored —
    // every perimeter edge is transmissive regardless of what the user
    // asked for in BOUNDARY_CONDITIONS.
    //
    // We rewrite each boundary edge's tag here:
    //   JSON tag N → type "wall"    ⇒ edge.boundary_tag = 3
    //   JSON tag N → type "outflow" ⇒ edge.boundary_tag = 1 (transmissive)
    // Tags that are not present in the JSON keep their original value.
    // Two-stage lookup:
    //   1. Per-tag mapping  (advanced: mesh with multiple physical groups
    //      like {"1": "wall", "2": "outflow"})
    //   2. Global default   (common: single "boundary" group generated by
    //      mesh_generation.py, typed uniformly). The default is picked
    //      from the first entry in the JSON; falls back to "outflow" if
    //      nothing is set. This handles the case where the mesh file
    //      didn't preserve the physical-group tag on individual edges
    //      and they all show up with boundary_tag == 0.
    std::map<int, int> tag_to_type;
    int default_solver_tag = 1;   // transmissive fallback
    bool saw_default = false;
    if (!ds.boundary_conditions_json.is_null()) {
        for (auto it = ds.boundary_conditions_json.begin();
             it != ds.boundary_conditions_json.end(); ++it) {
            int json_tag = 0;
            try { json_tag = std::stoi(it.key()); }
            catch (...) { continue; }
            std::string type_str = "outflow";
            if (it.value().is_object() && it.value().contains("type")) {
                type_str = it.value()["type"].get<std::string>();
            } else if (it.value().is_string()) {
                type_str = it.value().get<std::string>();
            }
            for (auto& c : type_str) c = std::tolower(c);
            int solver_tag = (type_str == "wall") ? 3 : 1;
            tag_to_type[json_tag] = solver_tag;
            if (!saw_default) {
                default_solver_tag = solver_tag;
                saw_default = true;
            }
        }
    }

    int walls = 0, outflows = 0;
    for (int ei = 0; ei < mesh.num_edges; ei++) {
        auto& edge = mesh.edges[ei];
        if (edge.is_boundary && edge.left_cell >= 0) {
            mesh.cells[edge.left_cell].is_boundary = true;

            auto it = tag_to_type.find(edge.boundary_tag);
            if (it != tag_to_type.end()) {
                edge.boundary_tag = it->second;
            } else {
                // No per-tag entry for this edge — apply the global
                // default from the first JSON entry (or outflow if none).
                edge.boundary_tag = default_solver_tag;
            }
            if (edge.boundary_tag == 3) walls++; else outflows++;
        }
    }
    std::cout << "  Boundary tags applied: "
              << walls << " wall edges, "
              << outflows << " outflow/transmissive edges" << std::endl;
}
