#!/usr/bin/env python3
"""
FLUXOS JSON configuration file generator.
Generates modset.json matching the format expected by read_modset() in read_functions.cpp.
"""

import json
import sys


def cmd_config(args):
    """
    CLI handler for the 'config' subcommand.
    Generates a FLUXOS modset.json configuration file.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed CLI arguments.
    """
    config = {}

    # Comment
    config["COMMENT"] = "Generated by fluxos_setup.py"

    # DEM file (required)
    config["DEM_FILE"] = args.dem_file

    # Simulation start time
    config["SIM_DATETIME_START"] = getattr(args, 'sim_start', "2000-01-01 00:00:00")

    # Restart option
    config["RESTART"] = getattr(args, 'restart', False)

    # Output settings (required by read_modset)
    config["OUTPUT"] = {
        "OUTPUT_FOLDER": args.output_folder,
        "PRINT_STEP": args.output_step,
        "H_MIN_TO_PRINT": getattr(args, 'h_min_print', 0.005)
    }

    # Roughness height (note: matches existing typo "ROUGNESS_HEIGHT" in codebase)
    config["ROUGNESS_HEIGHT"] = args.roughness

    # External modules
    config["EXTERNAL_MODULES"] = {
        "ADE_TRANSPORT": {
            "STATUS": getattr(args, 'ade_status', False),
            "D_COEF": getattr(args, 'ade_dcoef', 0.5)
        },
        "OPENWQ": {
            "STATUS": getattr(args, 'openwq_status', False),
            "MASTERFILE_DIR": getattr(args, 'openwq_masterfile', "")
        }
    }

    # Forcing: meteo file
    if args.meteo_file:
        config["METEO_FILE"] = args.meteo_file

    # Forcing: inflow file
    if args.inflow_file:
        inflow_config = {
            "FILENAME": args.inflow_file,
            "DISCHARGE_LOCATION": {
                "X_COORDINATE": int(args.inflow_x) if args.inflow_x else 0,
                "Y_COORDINATE": int(args.inflow_y) if args.inflow_y else 0
            }
        }
        config["INFLOW_FILE"] = inflow_config

    # Check at least one forcing is provided
    if not args.meteo_file and not args.inflow_file:
        print("WARNING: No forcing file specified (--meteo-file or --inflow-file).")
        print("  FLUXOS requires at least one forcing source.")

    # Mesh type (regular or triangular)
    if args.mesh_type == "triangular":
        config["MESH_TYPE"] = "triangular"

        if not args.mesh_file:
            print("ERROR: --mesh-file is required when --mesh-type is triangular")
            sys.exit(1)

        config["MESH_FILE"] = args.mesh_file
        config["MESH_FORMAT"] = getattr(args, 'mesh_format', "gmsh")

        # Boundary conditions (optional)
        bc_str = getattr(args, 'boundary_conditions', None)
        if bc_str:
            try:
                config["BOUNDARY_CONDITIONS"] = json.loads(bc_str)
            except json.JSONDecodeError:
                print(f"WARNING: Could not parse --boundary-conditions as JSON: {bc_str}")
                config["BOUNDARY_CONDITIONS"] = {"1": {"type": "wall"}}
        else:
            config["BOUNDARY_CONDITIONS"] = {"1": {"type": "wall"}}

    # Write config file
    output_path = args.output
    with open(output_path, 'w') as f:
        json.dump(config, f, indent=4)

    print(f"\nConfig written to: {output_path}")
    print(f"  DEM file:     {args.dem_file}")
    print(f"  Mesh type:    {args.mesh_type}")
    if args.mesh_type == "triangular":
        print(f"  Mesh file:    {args.mesh_file}")
    if args.meteo_file:
        print(f"  Meteo file:   {args.meteo_file}")
    if args.inflow_file:
        print(f"  Inflow file:  {args.inflow_file}")
    print(f"  Output step:  {args.output_step}s")
    print(f"  Roughness:    {args.roughness}m")
